### ISSUE TITLE
如何编译

### ISSUE THREAD

**Issue by SuperXiaoxiong** [woodpecker-framework/woodpecker-bcel#1]
编译报错：mvn package
woodpecker-bcel/src/main/java/me/gv7/woodpecker/bcel/util/InstructionFinder.java:[64,1] 程序包com.sun.org.apache.regexp.internal不存在

**Comment by c0ny1** [comment]
你的jdk版本是多少

**Comment by c0ny1** [comment]
使用maven直接拉即可
